stages:
- build

linux:
    stage: build
    script: 
        - apt-get update
        - apt-get install --no-install-recommends xz-utils curl ca-certificates git -y
        - git submodule init && git submodule update
        - curl -L https://github.com/AnarchyTools/atbuild/releases/download/0.10.0/atbuild-0.10.0-linux.tar.xz | tar xJ  && cp atbuild-*/atbuild /usr/local/bin/atbuild
        - atbuild check
    tags:
        - autoscale-linux
    image: drewcrawford/swift:latest

osx:
    stage: build
    script: 
        - git submodule init && git submodule update
        - atbuild check
    tags:
        - openswift
        - atbuild
