stages:
- build

linux:
    stage: build
    script: 
        - docker build . --rm=true
    tags:
        - docker
osx:
    stage: build
    script: 
        - atbuild run-tests
    tags:
        - openswift
        - atbuild
