stages:
- build

linux:
    stage: build
    script: 
        - docker build --rm=true .
    tags:
        - docker
osx:
    stage: build
    script: 
        - atbuild check
    tags:
        - openswift
        - atbuild
