stages:
- build

linux:
    stage: build
    script: 
        - apt-get update
        - apt-get install atbuild
        - git submodule update --init --recursive
        - atbuild check
    tags:
        - autoscale-linux
    image: drewcrawford/buildbase:latest

osx:
    stage: build
    script: 
        - git submodule init && git submodule update
        - atbuild check
    tags:
        - openswift
        - atbuild
